spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/amazon
    username: springuser
    password: ThePassword
    driver-class-name: org.postgresql.Driver
